modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/TheGasMan2/Create-Biomechanical/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="examplemod.png" #optional

#credits="" #optional

authors = "${mod_authors}"
description = '''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
type = "required"
versionRange = "${create_version_range}"
ordering = "BEFORE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "smartbrainlib"
type = "required"
versionRange = "[1.16,2.0)"
ordering = "BEFORE"
side = "SERVER"

[[dependencies."${mod_id}"]]
modId = "geckolib"
type = "required"
versionRange = "[4.7,5.0)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "multipart_api"
type = "required"
versionRange = "[${multipart_api_version},)"
ordering = "BEFORE"
side = "BOTH"

